### ISSUE TITLE
Error when running dcli

### ISSUE THREAD

**Issue by hamburgerghini1** [Dashlane/dashlane-cli#198]
**Describe the bug**
Got this error after installing from brew and running dcli.

pkg/prelude/bootstrap.js:1872
      throw error;
      ^

Error: Cannot find module '@napi-rs/keyring-linux-x64-gnu'
Require stack:
- /snapshot/dashlane-cli-1.15.0/node_modules/@napi-rs/keyring/index.js
- /snapshot/dashlane-cli-1.15.0/dist/modules/crypto/keychainManager.js
- /snapshot/dashlane-cli-1.15.0/dist/modules/database/reset.js
- /snapshot/dashlane-cli-1.15.0/dist/modules/database/connectAndPrepare.js
- /snapshot/dashlane-cli-1.15.0/dist/modules/database/index.js
- /snapshot/dashlane-cli-1.15.0/dist/command-handlers/backup.js
- /snapshot/dashlane-cli-1.15.0/dist/command-handlers/index.js
- /snapshot/dashlane-cli-1.15.0/dist/commands/devices.js
- /snapshot/dashlane-cli-1.15.0/dist/commands/index.js
- /snapshot/dashlane-cli-1.15.0/dist/index.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Module._resolveFilename (node:internal/modules/cjs/loader:946:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1951:46)
    at Module._load (node:internal/modules/cjs/loader:787:27)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/snapshot/dashlane-cli-1.15.0/node_modules/@napi-rs/keyring/index.js:190:31)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Module._compile (pkg/prelude/bootstrap.js:1933:32)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/snapshot/dashlane-cli-1.15.0/node_modules/@napi-rs/keyring/index.js',
    '/snapshot/dashlane-cli-1.15.0/dist/modules/crypto/keychainManager.js',
    '/snapshot/dashlane-cli-1.15.0/dist/modules/database/reset.js',
    '/snapshot/dashlane-cli-1.15.0/dist/modules/database/connectAndPrepare.js',
    '/snapshot/dashlane-cli-1.15.0/dist/modules/database/index.js',
    '/snapshot/dashlane-cli-1.15.0/dist/command-handlers/backup.js',
    '/snapshot/dashlane-cli-1.15.0/dist/command-handlers/index.js',
    '/snapshot/dashlane-cli-1.15.0/dist/commands/devices.js',
    '/snapshot/dashlane-cli-1.15.0/dist/commands/index.js',
    '/snapshot/dashlane-cli-1.15.0/dist/index.js'
  ],
  pkg: true
}

Node.js v18.5.0

**To Reproduce**
1. Run 'dcli'
2. See error

**Environment (please complete the following information):**
 - OS: Fedora 39

**Comment by Mikescops** [comment]
Hello,

Thanks for reporting, I haven't tested brew for linux on this OS. I'll have a look.

Meanwhile I recommend using the linux binary from the release: https://github.com/Dashlane/dashlane-cli/releases/tag/v1.15.0

**Comment by Mikescops** [comment]
Hello @hamburgerghini1,

I took the time to test on Fedora 40 with the release 6.2421.0 and everything was working well.

<img width="736" alt="image" src="https://github.com/Dashlane/dashlane-cli/assets/4266283/fde94056-b5e3-444d-87b9-f8751ed78bdf">

I'm closing this issue for now, feel free to reopen if you find something else.
