### ISSUE TITLE
Clipboard copy does not work on WSL2

### ISSUE THREAD

**Issue by damienwebdev** [Dashlane/dashlane-cli#45]
```
? Please enter your master password: [hidden]
? What password would you like to get? My Password
Error: spawnSync /snapshot/dashlane-cli/node_modules/clipboardy/fallbacks/windows/clipboard_x86_64.exe ENOENT
    at Object.spawnSync (node:internal/child_process:1111:20)
    at Object.spawnSync (node:child_process:814:24)
    at Object.spawnSync (pkg/prelude/bootstrap.js:2087:31)
    at Function.sync (/snapshot/dashlane-cli/node_modules/execa/index.js:334:30)
    at Object.copySync (/snapshot/dashlane-cli/node_modules/clipboardy/lib/windows.js:14:29)
    at Object.<anonymous> (/snapshot/dashlane-cli/node_modules/clipboardy/index.js:45:14)
    at getPassword (/snapshot/dashlane-cli/dist/middleware/getPasswords.js:95:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Command.<anonymous> (/snapshot/dashlane-cli/dist/index.js:55:9)
    at async Command.parseAsync (/snapshot/dashlane-cli/node_modules/commander/lib/command.js:917:5) {
  errno: -2,
  ```
  
  Looks like the CLI thinks I'm on windows within my WSL2 VM.

**Comment by Mikescops** [comment]
Hello,
you did not share the command you used but given the error, it seems that it's the copy to clipboard functionality that has an issue. I think it makes sense that ultimately it fallback to windows when it does not recognize the operating system. The dependency we are using to support clipboard might not be compatible with WSL. I think this should be reported there.

Can you confirm that using other output modes like JSON it is fine?

**Comment by Booyaabes** [comment]
Same problem here, on WSL and PowerShell:

```
PS> dcli password --debug
debug:   Connected to database.
debug:   Retrieving:
? What password would you like to get? ************ - *****************@******.***
Error: spawnSync C:\snapshot\dashlane-cli\node_modules\clipboardy\fallbacks\windows\clipboard_x86_64.exe ENOENT
    at Object.spawnSync (node:internal/child_process:1111:20)
    at Object.spawnSync (node:child_process:814:24)
    at Object.spawnSync (pkg/prelude/bootstrap.js:2087:31)
    at Function.sync (C:\snapshot\dashlane-cli\node_modules\execa\index.js:334:30)
    at Object.copySync (C:\snapshot\dashlane-cli\node_modules\clipboardy\lib\windows.js:14:29)
    at Object.<anonymous> (C:\snapshot\dashlane-cli\node_modules\clipboardy\index.js:45:14)
    at getPassword (C:\snapshot\dashlane-cli\dist\middleware\getPasswords.js:95:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Command.<anonymous> (C:\snapshot\dashlane-cli\dist\index.js:55:9)
    at async Command.parseAsync (C:\snapshot\dashlane-cli\node_modules\commander\lib\command.js:917:5) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawnSync C:\\snapshot\\dashlane-cli\\node_modules\\clipboardy\\fallbacks\\windows\\clipboard_x86_64.exe',
  path: 'C:\\snapshot\\dashlane-cli\\node_modules\\clipboardy\\fallbacks\\windows\\clipboard_x86_64.exe',
  spawnargs: [ '--copy' ],
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd: 'C:\\snapshot\\dashlane-cli\\node_modules\\clipboardy\\fallbacks\\windows\\clipboard_x86_64.exe --copy',
  timedOut: false
}
```

It works fine if I choose json or password output.

Of course "C:\\snapshot\\dashlane-cli\\node_modules\\clipboardy\\fallbacks\\windows\\clipboard_x86_64.exe" does not exist on my computer. I installed dcli.exe from GitHub release.

**Comment by Booyaabes** [comment]
I confirm that download [clipboard_x86_64.exe](https://github.com/sindresorhus/clipboardy/blob/main/fallbacks/windows/clipboard_x86_64.exe) in "C:\snapshot\dashlane-cli\node_modules\clipboardy\fallbacks\windows\clipboard_x86_64.exe" make it work.

**Comment by Mikescops** [comment]
Thanks a lot @Booyaabes for the debugging this, I'll have a look when I have more time on how to better support WSL2.

**Comment by sebastienbaillet** [comment]
FYI, I've just made some tests, dcli 1.4.0 resolve Windows Clipboard issue.

**Comment by Mikescops** [comment]
@sebastienbaillet Yes, we fixed that, thanks for the double check, but it still doesn't work on WSL, @jboillot made a PR earlier on the dependency we're using to support it

**Comment by sebastienbaillet** [comment]
Thank you for the great work :)

**Comment by Mikescops** [comment]
Will be included in the next release.
