### ISSUE TITLE
OTP starting with 0 returns an error

### ISSUE THREAD

**Issue by BenjaminOddou** [Dashlane/dashlane-cli#69]
Hello,

It seems that OTP starting with a 0 results automatically an error. See below (from `v1.0.0`):

```shell
! ! ! input was 058899 ! ! !
? Please enter your OTP code: 58899
DashlaneApiError: The OTP verification failed. This could be due for example to the user inputing a wrong token.
    at requestApi (/snapshot/dashlane-cli/dist/requestApi.js:79:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async registerDevice (/snapshot/dashlane-cli/dist/middleware/registerDevice.js:31:27)
    at async getSecretsWithoutDB (/snapshot/dashlane-cli/dist/crypto/keychainManager.js:81:50)
    at async connectAndPrepare (/snapshot/dashlane-cli/dist/database/connectAndPrepare.js:24:21)
    at async Command.<anonymous> (/snapshot/dashlane-cli/dist/index.js:34:29)
    at async Command.parseAsync (/snapshot/dashlane-cli/node_modules/commander/lib/command.js:917:5) {
  code: 'verification_failed',
  type: 'business_error'
}
```

Note : I am on macos Ventura 13.2.1 (22D68) - Dashlane CLI 1.0.0

**Comment by Mikescops** [comment]
Hello,

Yes you're right the offending line is https://github.com/Dashlane/dashlane-cli/blob/master/src/middleware/registerDevice.ts#L35

@ni0ki spotted this issue earlier too

It needs to be fixed.
